name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: "platform-tools build-tools;36.0.0 platforms;android-36"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get short commit hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Rename APK with release-tarih-soncommit
        run: |
          build_date=$(date +"%Y-%m-%d-%H%M%S")
          commit_hash=${{ steps.vars.outputs.commit_hash }}
          mkdir -p artifacts
          for apk in app/build/outputs/apk/release/*.apk; do
            cp "$apk" "artifacts/release-$build_date-$commit_hash.apk"
          done

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.run_number }}-${{ steps.vars.outputs.commit_hash }}
          path: artifacts/release-*.apk
